---

plugins:
  - jest

env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  # Отключаем проблемные правила
  arrow-parens: off
  semi: off
  comma-dangle: off
  # Дополнительные стилистические правила которые могут мешать
  operator-linebreak: off
  implicit-arrow-linebreak: off
  function-paren-newline: off
